#!/usr/bin/env bash

npx @bookshop/generate

npx rosey-cloudcannon-connector tag --source _site
npx rosey generate --source _site
npx rosey-cloudcannon-connector generate

echo "Translating site with Rosey"
mv ./_site ./untranslated_site                  
npx rosey build --source untranslated_site --dest _site --default-language-at-root
